version: "3.9"

services:

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: drkiq
      POSTGRES_PASSWORD: test_db_password
    ports: 
      - '5491:5432'
    volumes:
      - drkiq-postgres:/var/lib/postgresql/data

  drkiq:
    build:
      context: .
    volumes:
      - ./drkiq:/opt/app
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  drkiq-postgres:
