# Use the official MySQL image as the base image
FROM mysql

# Set environment variables for MySQL root user password
ENV MYSQL_ROOT_PASSWORD=mysecretpassword

# Expose the default MySQL port
EXPOSE 3306

# Optionally, you can add additional configuration or initialization steps here

# CMD instruction to start MySQL when a container is run
CMD ["mysqld"]
