version: "3.9"

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-1205}
    ports: 
      - '5432:5432'
    volumes:
      - database-postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
    volumes:
      # - ./rails_app:/opt/app 
      - ./${RAILS_APP_NAME}:/opt/app 
    links:
      - postgres
    ports:
      - '3000:3000'
    env_file:
      - .env
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && rails server -b 0.0.0.0"
volumes:
  database-postgres:

# version: '3.5'
# services:
#   db:
#     image: postgres
#     volumes:
#       - ./tmp/db:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: password
#   redis:
#     image: redis
#     command: redis-server
#     volumes:
#       - 'redis:/data'
#   web:
#     build: .
#     command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     volumes:
#       - .:/myapp
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#       - redis
#     environment:
#       - REDIS_URL_CACHING=redis://redis:6379/0
#       - DATABASE_HOST=db
#       - DATABASE_USERNAME=postgres
#       - DATABASE_PASSWORD=password

# volumes:
#   redis:
#   postgres:
