source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.3"
# gem "sprockets-rails"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "bootsnap", require: false
gem 'dotenv-rails'

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "better_errors"
  gem "binding_of_caller"
  gem "faker"
  gem 'prettier'
  # gem "pry-rails"
end

group :development do
  gem "web-console"
  # bundle exec erd
  gem 'rails-erd'
  gem 'annotate'
  gem 'spring'
  gem 'listen'
  gem 'spring-watcher-listen'
  # gem 'honeybadger'
  gem 'rorvswild'
  gem 'lograge'
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem 'webdrivers'
end
